---
title: "Modify Raw Imported Data"
author: "Jonathan Salas"
date: "Last Updated `r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
knitr::opts_knit$set(root.dir = "~/R_Projects/VCAS1_prelim_efficiency")
```

# Import the raw data - Point to the correct raw data directory

```{r}
raw_data_dir <-"data/processed/imported_efficiency_stats.RData"
```


## Import Subject Data
```{r}
load(raw_data_dir)
```

## Calculate derived statistics

proc_vs_rove is procedure time (seconds) as a function of rove_time (seconds)
rove_per_app is rove time (s) as a function of number of applications

```{r}
cleaned_res <- cleaned_res |>
  mutate(
    proc_vs_rove = round(procedure_time/rove_time,2),
    rove_per_app = round(rove_time/num_applications)
  ) 
```

# Save cleaned data

```{r}
save(cleaned_res, 
     file = paste0("data/processed/working_efficiency_stats.RData"))
```

# Version and Package Details

```{r echo=F}
paste(version$version.string, version$nickname)
paste0(
  "RStudio Version ",
  rstudioapi::versionInfo()$version,
  " ",
  rstudioapi::versionInfo()$release_name
) # RStudio Version
subset(data.frame(sessioninfo::package_info()),
       attached == TRUE,
       c(package, loadedversion)) # Loaded Packages
```

# When were these files last rewritten?

```{r}
date()
```